http_port 3128

acl github dstdomain .github.com
acl githubusercontent dstdomain .githubusercontent.com
acl githubassets dstdomain .githubassets.com

acl npm dstdomain .npmjs.org
acl npmregistry dstdomain .registry.npmjs.org

http_access allow github
http_access allow githubusercontent
http_access allow githubassets

http_access allow npm
http_access allow npmregistry

http_access deny all